[workspace]
resolver = "2"
members = ["demo_00", "demo_01", "demo_02", "demo_03", "demo_04", "demo_05", "demo_06", "demo_07", "demo_08", "demo_09", "demo_10", "demo_11", "demo_12", "demo_13", "demo_14", "demo_15", "demo_16", "demo_17", "demo_18", "demo_19"]
